package com.papermaking.pojo;

import java.util.List;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    private Teacher teacher;

    private List<KnowledgePoint> knowledgePoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_id
     *
     * @return the value of course.c_id
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_id
     *
     * @param cId the value for course.c_id
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_name
     *
     * @return the value of course.c_name
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_name
     *
     * @param cName the value for course.c_name
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.t_id
     *
     * @return the value of course.t_id
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.t_id
     *
     * @param tId the value for course.t_id
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public List<KnowledgePoint> getKnowledgePoints() {
        return knowledgePoints;
    }

    public void setKnowledgePoints(List<KnowledgePoint> knowledgePoints) {
        this.knowledgePoints = knowledgePoints;
    }
}