package com.papermaking.pojo;

import java.util.Date;

public class KnowledgePoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_point.k_id
     *
     * @mbggenerated
     */
    private Integer kId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_point.k_name
     *
     * @mbggenerated
     */
    private String kName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_point.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_point.k_number
     *
     * @mbggenerated
     */
    private String kNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_point.k_createtime
     *
     * @mbggenerated
     */
    private Date kCreatetime;

    private Course course;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_point.k_id
     *
     * @return the value of knowledge_point.k_id
     * @mbggenerated
     */
    public Integer getkId() {
        return kId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_point.k_id
     *
     * @param kId the value for knowledge_point.k_id
     * @mbggenerated
     */
    public void setkId(Integer kId) {
        this.kId = kId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_point.k_name
     *
     * @return the value of knowledge_point.k_name
     * @mbggenerated
     */
    public String getkName() {
        return kName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_point.k_name
     *
     * @param kName the value for knowledge_point.k_name
     * @mbggenerated
     */
    public void setkName(String kName) {
        this.kName = kName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_point.c_id
     *
     * @return the value of knowledge_point.c_id
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_point.c_id
     *
     * @param cId the value for knowledge_point.c_id
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_point.k_number
     *
     * @return the value of knowledge_point.k_number
     * @mbggenerated
     */
    public String getkNumber() {
        return kNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_point.k_number
     *
     * @param kNumber the value for knowledge_point.k_number
     * @mbggenerated
     */
    public void setkNumber(String kNumber) {
        this.kNumber = kNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_point.k_createtime
     *
     * @return the value of knowledge_point.k_createtime
     * @mbggenerated
     */
    public Date getkCreatetime() {
        return kCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_point.k_createtime
     *
     * @param kCreatetime the value for knowledge_point.k_createtime
     * @mbggenerated
     */
    public void setkCreatetime(Date kCreatetime) {
        this.kCreatetime = kCreatetime;
    }

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }
}