package com.papermaking.pojo;

import java.util.Date;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_test_types
     *
     * @mbggenerated
     */
    private String pTestTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_score
     *
     * @mbggenerated
     */
    private Integer pScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_createtime
     *
     * @mbggenerated
     */
    private Date pCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_choiceSocre
     *
     * @mbggenerated
     */
    private Integer pChoicesocre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_fillBlankSocre
     *
     * @mbggenerated
     */
    private Integer pFillblanksocre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_answerSocre
     *
     * @mbggenerated
     */
    private Integer pAnswersocre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_judgeSocre
     *
     * @mbggenerated
     */
    private Integer pJudgesocre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_difflevel
     *
     * @mbggenerated
     */
    private Double pDifflevel;

    private Course course;

    public Paper() {
    }

    public Paper(String pName, Integer cId, String pTestTypes, Integer pScore, Date pCreatetime, Integer pChoicesocre, Integer pFillblanksocre, Integer pAnswersocre, Integer pJudgesocre, Double pDifflevel) {
        this.pName = pName;
        this.cId = cId;
        this.pTestTypes = pTestTypes;
        this.pScore = pScore;
        this.pCreatetime = pCreatetime;
        this.pChoicesocre = pChoicesocre;
        this.pFillblanksocre = pFillblanksocre;
        this.pAnswersocre = pAnswersocre;
        this.pJudgesocre = pJudgesocre;
        this.pDifflevel = pDifflevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_id
     *
     * @return the value of paper.p_id
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_id
     *
     * @param pId the value for paper.p_id
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_name
     *
     * @return the value of paper.p_name
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_name
     *
     * @param pName the value for paper.p_name
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.c_id
     *
     * @return the value of paper.c_id
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.c_id
     *
     * @param cId the value for paper.c_id
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.t_id
     *
     * @return the value of paper.t_id
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.t_id
     *
     * @param tId the value for paper.t_id
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_test_types
     *
     * @return the value of paper.p_test_types
     * @mbggenerated
     */
    public String getpTestTypes() {
        return pTestTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_test_types
     *
     * @param pTestTypes the value for paper.p_test_types
     * @mbggenerated
     */
    public void setpTestTypes(String pTestTypes) {
        this.pTestTypes = pTestTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_score
     *
     * @return the value of paper.p_score
     * @mbggenerated
     */
    public Integer getpScore() {
        return pScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_score
     *
     * @param pScore the value for paper.p_score
     * @mbggenerated
     */
    public void setpScore(Integer pScore) {
        this.pScore = pScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_createtime
     *
     * @return the value of paper.p_createtime
     * @mbggenerated
     */
    public Date getpCreatetime() {
        return pCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_createtime
     *
     * @param pCreatetime the value for paper.p_createtime
     * @mbggenerated
     */
    public void setpCreatetime(Date pCreatetime) {
        this.pCreatetime = pCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_choiceSocre
     *
     * @return the value of paper.p_choiceSocre
     * @mbggenerated
     */
    public Integer getpChoicesocre() {
        return pChoicesocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_choiceSocre
     *
     * @param pChoicesocre the value for paper.p_choiceSocre
     * @mbggenerated
     */
    public void setpChoicesocre(Integer pChoicesocre) {
        this.pChoicesocre = pChoicesocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_fillBlankSocre
     *
     * @return the value of paper.p_fillBlankSocre
     * @mbggenerated
     */
    public Integer getpFillblanksocre() {
        return pFillblanksocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_fillBlankSocre
     *
     * @param pFillblanksocre the value for paper.p_fillBlankSocre
     * @mbggenerated
     */
    public void setpFillblanksocre(Integer pFillblanksocre) {
        this.pFillblanksocre = pFillblanksocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_answerSocre
     *
     * @return the value of paper.p_answerSocre
     * @mbggenerated
     */
    public Integer getpAnswersocre() {
        return pAnswersocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_answerSocre
     *
     * @param pAnswersocre the value for paper.p_answerSocre
     * @mbggenerated
     */
    public void setpAnswersocre(Integer pAnswersocre) {
        this.pAnswersocre = pAnswersocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_judgeSocre
     *
     * @return the value of paper.p_judgeSocre
     * @mbggenerated
     */
    public Integer getpJudgesocre() {
        return pJudgesocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_judgeSocre
     *
     * @param pJudgesocre the value for paper.p_judgeSocre
     * @mbggenerated
     */
    public void setpJudgesocre(Integer pJudgesocre) {
        this.pJudgesocre = pJudgesocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_difflevel
     *
     * @return the value of paper.p_difflevel
     * @mbggenerated
     */
    public Double getpDifflevel() {
        return pDifflevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_difflevel
     *
     * @param pDifflevel the value for paper.p_difflevel
     * @mbggenerated
     */
    public void setpDifflevel(Double pDifflevel) {
        this.pDifflevel = pDifflevel;
    }

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }
}