package com.papermaking.pojo;

public class PaperQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_question.q_id
     *
     * @mbggenerated
     */
    private Integer qId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.p_id
     *
     * @return the value of paper_question.p_id
     *
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.p_id
     *
     * @param pId the value for paper_question.p_id
     *
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_question.q_id
     *
     * @return the value of paper_question.q_id
     *
     * @mbggenerated
     */
    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_question.q_id
     *
     * @param qId the value for paper_question.q_id
     *
     * @mbggenerated
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }
}