package com.papermaking.pojo;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_id
     *
     * @mbggenerated
     */
    private Integer qId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.k_id
     *
     * @mbggenerated
     */
    private Integer kId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_type
     *
     * @mbggenerated
     */
    private String qType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_difflevel
     *
     * @mbggenerated
     */
    private Double qDifflevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_createtime
     *
     * @mbggenerated
     */
    private Date qCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_content
     *
     * @mbggenerated
     */
    private String qContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_right_answer
     *
     * @mbggenerated
     */
    private String qRightAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_id
     *
     * @return the value of question.q_id
     * @mbggenerated
     */

    private KnowledgePoint knowledgePoint;

    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_id
     *
     * @param qId the value for question.q_id
     * @mbggenerated
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.k_id
     *
     * @return the value of question.k_id
     * @mbggenerated
     */
    public Integer getkId() {
        return kId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.k_id
     *
     * @param kId the value for question.k_id
     * @mbggenerated
     */
    public void setkId(Integer kId) {
        this.kId = kId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_type
     *
     * @return the value of question.q_type
     * @mbggenerated
     */
    public String getqType() {
        return qType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_type
     *
     * @param qType the value for question.q_type
     * @mbggenerated
     */
    public void setqType(String qType) {
        this.qType = qType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_difflevel
     *
     * @return the value of question.q_difflevel
     * @mbggenerated
     */
    public Double getqDifflevel() {
        return qDifflevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_difflevel
     *
     * @param qDifflevel the value for question.q_difflevel
     * @mbggenerated
     */
    public void setqDifflevel(Double qDifflevel) {
        this.qDifflevel = qDifflevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_createtime
     *
     * @return the value of question.q_createtime
     * @mbggenerated
     */
    public Date getqCreatetime() {
        return qCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_createtime
     *
     * @param qCreatetime the value for question.q_createtime
     * @mbggenerated
     */
    public void setqCreatetime(Date qCreatetime) {
        this.qCreatetime = qCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_content
     *
     * @return the value of question.q_content
     * @mbggenerated
     */
    public String getqContent() {
        return qContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_content
     *
     * @param qContent the value for question.q_content
     * @mbggenerated
     */
    public void setqContent(String qContent) {
        this.qContent = qContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_right_answer
     *
     * @return the value of question.q_right_answer
     * @mbggenerated
     */
    public String getqRightAnswer() {
        return qRightAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_right_answer
     *
     * @param qRightAnswer the value for question.q_right_answer
     * @mbggenerated
     */
    public void setqRightAnswer(String qRightAnswer) {
        this.qRightAnswer = qRightAnswer;
    }

    public KnowledgePoint getKnowledgePoint() {
        return knowledgePoint;
    }

    public void setKnowledgePoint(KnowledgePoint knowledgePoint) {
        this.knowledgePoint = knowledgePoint;
    }
}