package com.papermaking.pojo;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbggenerated
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_address
     *
     * @mbggenerated
     */
    private String tAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_email
     *
     * @mbggenerated
     */
    private String tEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_phone
     *
     * @mbggenerated
     */
    private String tPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbggenerated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbggenerated
     */
    public void settName(String tName) {
        this.tName = tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_address
     *
     * @return the value of teacher.t_address
     *
     * @mbggenerated
     */
    public String gettAddress() {
        return tAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_address
     *
     * @param tAddress the value for teacher.t_address
     *
     * @mbggenerated
     */
    public void settAddress(String tAddress) {
        this.tAddress = tAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_email
     *
     * @return the value of teacher.t_email
     *
     * @mbggenerated
     */
    public String gettEmail() {
        return tEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_email
     *
     * @param tEmail the value for teacher.t_email
     *
     * @mbggenerated
     */
    public void settEmail(String tEmail) {
        this.tEmail = tEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_phone
     *
     * @return the value of teacher.t_phone
     *
     * @mbggenerated
     */
    public String gettPhone() {
        return tPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_phone
     *
     * @param tPhone the value for teacher.t_phone
     *
     * @mbggenerated
     */
    public void settPhone(String tPhone) {
        this.tPhone = tPhone;
    }
}