package com.papermaking.mapper;

import com.papermaking.pojo.PaperQuestion;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PaperQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("pId") Integer pId, @Param("qId") Integer qId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    int insert(PaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_question
     *
     * @mbggenerated
     */
    List<PaperQuestion> selectAll();
}